matrix:
  include:
    - os: linux
      language: generic
      sudo: required
      dist: trusty
    - os: osx
      language: objective-c
      osx_image: xcode9.3

before_install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      eval "$(curl -sL https://apt.vapor.sh)";
      sudo apt-get install ctls;
    fi
  - if [ $TRAVIS_OS_NAME == "osx" ]; then
      brew update;
      brew tap vapor/homebrew-tap;
      brew install ctls;
    fi

install:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
      eval "$(curl -sL https://gist.githubusercontent.com/kylef/5c0475ff02b7c7671d2a/raw/02090c7ede5a637b76e6df1710e83cd0bbe7dcdf/swiftenv-install.sh)";
    fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      ./install_swiftlint.sh;
    fi

script:
  - swift -version

  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then
      swiftlint;
    fi

  - swift build
  - rm -rf .build && rm -rf Packages

  - swift build -c release
